### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by SeamusFinlayson** [nboughton/obr-dragonbane-initiative#1]
After adding tokens to the initiative and reloading a scene the extension will fail to load

![image](https://github.com/user-attachments/assets/ac25af7e-f661-4068-a08e-7a0d92b419cf)

This error is logged in the console

![image](https://github.com/user-attachments/assets/ae9a096b-85d4-47fd-aba8-c2837a3cd2c5)

Moving a token after this error causes the extension to work properly again, so looks like the initial call to the scene fails or something without fallback data.

**Comment by SeamusFinlayson** [comment]
I submitted pr #2 to fix this and a problem with the background color

**Comment by nboughton** [comment]
PR merged and deployed.
